name: Validate Run
on:
  push:
    branches: [ feature/monorepo, feature/monorepo-build]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflow
        uses: ./
        with:
          workflow: Version Bump (develop)
          token: ${{ secrets.REPO_GHA_PAT }}

