name: Validate Run
on:
  push:
    branches: [ feature/monorepo, feature/monorepo-build]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
