name: Validate Run
on:
  push:
    branches: [ feature/monorepo, feature/monorepo-build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Trigger next workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Version Bump for Develop
        token: ${{ secrets.REPO_GHA_PAT }}